name: Deploy to ECS

on:
  push:
    branches:
      - test  # Change to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        uses: docker/login-action@v2
        with:
          registry: 730335620727.dkr.ecr.us-east-1.amazonaws.com
          username: AWS
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and push Docker image
        run: |
          docker build -t my-web-app .
          docker push 730335620727.dkr.ecr.us-east-1.amazonaws.com/my-web-app:latest

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update ECS service
        run: |
          TASK_DEFINITION_ARN=$(aws ecs describe-task-definition --task-definition defination --query 'taskDefinition.taskDefinitionArn' --output text)
          aws ecs update-service --cluster ${{ secrets.ECS_CLUSTER_NAME }} --service ${{ secrets.ECS_SERVICE_NAME }} --force-new-deployment --task-definition $TASK_DEFINITION_ARN
