name: CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t my-web-app .

      - name: Tag Docker image
        run: |
          docker tag my-web-app:latest 730335620727.dkr.ecr.us-east-1.amazonaws.com/my-web-app:latest

      - name: Push Docker image to Amazon ECR
        run: |
          docker push 730335620727.dkr.ecr.us-east-1.amazonaws.com/my-web-app:latest

      - name: Update ECS task definition
        id: update-task-def
        run: |
          ecs-cli configure --region us-east-1 --config-name ecs-config
          ecs-cli compose --file docker-compose.yml --project-name my-web-app create
          ecs-cli compose --file docker-compose.yml --project-name my-web-app service up
          # Alternatively, use AWS CLI to register task definition
          aws ecs register-task-definition \
            --cli-input-json file://ecs-task-definition.json

      - name: Deploy updated task definition to ECS
        run: |
          aws ecs update-service \
            --cluster my-cluster \
            --service my-service \
            --task-definition my-task-definition
